### ISSUE TITLE
numpy 2.0 update  causing errors in portray server

### ISSUE THREAD

**Issue by phoughton** [timothycrosley/portray#108]
Hello, 

Hope you can help, 

portray errors when i run `portray serve` and it looks to be caused by the recent numpy update.

Using:
Python 3.11.4
portray==1.8.0

I see this error 
```
$ portray server
Traceback (most recent call last):
  File "/home/vscode/.local/bin/portray", line 5, in <module>
    from portray.cli import __hug__
  File "/home/vscode/.local/lib/python3.11/site-packages/portray/cli.py", line 14, in <module>
    import hug
  File "/home/vscode/.local/lib/python3.11/site-packages/hug/__init__.py", line 36, in <module>
    from hug import (
  File "/home/vscode/.local/lib/python3.11/site-packages/hug/output_format.py", line 145, in <module>
    @json_convert(str, numpy.unicode_)
                       ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead.
```

Thanks
Pete

**Comment by janos-takacs-evosoft-com** [comment]
This issue is impacting our team too, after testing, we have to downgrade numpy to 1.26 to be able to create the API doc.

Will this issue be ever fixed in this repo?
Did someone already fork this repo and fixed the issue?
Or could someone recommend a similar tool that is up to date with dependencies?
